# Generated by Django 4.1.7 on 2024-03-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
    ]
